"use client";

import React, { useState } from "react";
import {
  UploadIcon,
  HomeIcon,
  NairaIcon,
  FunnelIcon,
  OrderIcon,
  CancelledIcon,
  DeliveredIcon,
  DoubledChevronDown,
  ArrowUpIcon,
  ArrowDownIcon,
  ChevronDownIcon,
  ExportIcon,
  VertIcon
} from "../../../../public/assets/icons/dashboardIcons";
import { Button, Select } from "@/components";
import "react-circular-progressbar/dist/styles.css";
import HeaderBox from "@/components/dashboard/HeaderBox";
import FulfillmentInvoice from "@/components/payment/fulfillment-invoice/fulfillmentInvoice";
import LogisticsInvoice from "@/components/payment/logistics-invoice/logisticsInvoice";
import { useUserStore } from "@/state";
type Props = {};

function Payment({  }: Props) {
  const [active, setActive] = useState(false);
  const user = useUserStore(_ => _.user);
  return (
    <div className="flex flex-col items-start justify-start w-full font-barlow">
      {/* first dashboard row */}
      <div className="flex justify-between w-full mb-7">
        <div className="flex flex-col items-start justify-normal">
          <h2 className="xl:text-3xl lg:text-2xl text-xl font-semibold text-[#464255]">
            Dashboard
          </h2>
          <p className="xl:text-lg lg:text-base text-sm font-normal text-[#a3a3a3]">
            Hi, {user!.fullName}. Welcome back to Komas500 Admin!
          </p>
        </div>

        <div className="flex">
          <Button
            type="submit"
            className="bg-primary_100 text-white text-center text-base font-semibold hover:opacity-80 w-[263px] font-barlow me-6 "
            // onClick={() => console.log("logged")}
          >
            <div className="me-2 bg-primary_500">
              <UploadIcon />
            </div>
            Upload product
          </Button>

          <div className="w-[263px] flex rounded-2xl shadow-sm bg-white items-center px-5 py-4">
            <div className="bg-[#D9F3EA] rounded-2xl flex items-center justify-center p-3 me-2">
              <FunnelIcon />
            </div>
            <div className="pe-3">
              <p className="text-lg fon-medium text-[#3E4954]">
                Filter Period{" "}
              </p>
              <p className="text-xs text-[#3E4954]">
                13 Jun 2023 - 21 Jul 2023
              </p>
            </div>
            <ChevronDownIcon />
          </div>
        </div>
      </div>

      {/* second dashboard row */}
      <div className="flex gap-4 w-full mb-7 overflow-x-auto whitespace-nowrap">
        <HeaderBox
          amount="N3448944"
          title="Summary of all profit revenue"
          icon={<NairaIcon width="30" height="30" />}
          duration="September 2024"
          color="#3bb77e80"
          // arrowIcon={
          //   <span className="p-1 rounded-full me-1 flex items-center justify-center w-[16px] h-[16px] bg-[#D9F3EA]">
          //     <ArrowUpIcon />
          //   </span>
          // }
        />
        <HeaderBox
          amount="N3448944"
          title="Total earnings on vendors product"
          icon={<NairaIcon width="30" height="30" />}
          duration="12% (September 2023)"
          color="#3bb77e80"
          arrowIcon={
            <span className="p-1 rounded-full me-1 flex items-center justify-center w-[16px] h-[16px] bg-[#D9F3EA]">
              <ArrowUpIcon />
            </span>
          }
        />
        <HeaderBox
          amount="75"
          title="Total earning on logistics"
          icon={<OrderIcon />}
          duration="4% (September 2023)"
          color="#f3aaff80"
          arrowIcon={
            <span className="p-1 rounded-full me-1 flex items-center justify-center w-[16px] h-[16px] bg-[#D9F3EA]">
              <ArrowUpIcon />
            </span>
          }
        />
        <HeaderBox
          amount="357"
          title="Total earning on fulfillment center or pickup stations"
          icon={<DeliveredIcon />}
          duration="4% (September 2023)"
          color="#ffe3a980"
          arrowIcon={
            <span className="p-1 rounded-full me-1 flex items-center justify-center w-[16px] h-[16px] bg-[#ff5b5b1a]">
              <ArrowDownIcon />
            </span>
          }
        />
        <HeaderBox
          amount="65"
          title="Total number of orders generated by shopmates"
          icon={<CancelledIcon />}
          duration="25% (September 2023)"
          color="#ffc2c280"
          arrowIcon={
            <span className="p-1 rounded-full me-1 flex items-center justify-center w-[16px] h-[16px] bg-[#D9F3EA]">
              <ArrowUpIcon />
            </span>
          }
        />
        <HeaderBox
          amount="65"
          title="Total commission earned by shopmates"
          icon={<CancelledIcon />}
          duration="25% (September 2023)"
          color="#ffc2c280"
          arrowIcon={
            <span className="p-1 rounded-full me-1 flex items-center justify-center w-[16px] h-[16px] bg-[#D9F3EA]">
              <ArrowUpIcon />
            </span>
          }
        />
      </div>

      {/* third dashboard row */}
      <div className="w-full mt-7 max-w-lg mx-auto border-[2px] border-black/20 py-5 flex items-center justify-center gap-10 rounded-full">
        {/* fulfillment invoice */}
        <div
          onClick={() => setActive(false)}
          className={`selectInvoice ${!active ? "text-[#A3A3A3]" : ""}`}
        >
          <p>Fulfillment invoice</p>
        </div>

        {/* logistics invoice */}

        <div
          onClick={() => setActive(true)}
          className={`selectInvoice ${active ? "text-[#A3A3A3]" : ""}`}
        >
          <p>logistics invoice</p>
        </div>
      </div>

      {/* fourth dashboard row */}
      {!active ? <FulfillmentInvoice /> : <LogisticsInvoice />}
    </div>
  );
}

export default Payment;
